### ISSUE TITLE
[Question] Can i use gocov to get code coverage report for a go application if my tests are written in another framework using python

### ISSUE THREAD

**Issue by pradeep-jukaria** [axw/gocov#100]

**Comment by axw** [comment]
Not directly, but you could use Go 1.20's new `go build -cover` flag to generate a coverage report (https://tip.golang.org/doc/go1.20#cover), and then convert using `gocov convert`.

**Comment by pradeep-jukaria** [comment]
@axw I tried the approach but the coverage file is not getting populated and not getting anything to convert using `gocov convert` as I am executing my python test framework test cases separately 

Can you please layout some steps for this if you have them?

**Comment by axw** [comment]
> Can you please layout some steps for this if you have them?

@pradeep-jukaria sorry, I do not - I have not done this myself.
