### ISSUE TITLE
go get failed for go1.16

### ISSUE THREAD

**Issue by zr526799544** [axw/gocov#109]
`go get: loading module retractions for github.com/axw/gocov@v1.0.0: parsing go.mod: go.mod:3: invalid go version '1.22.0': must match format 1.23`

**Comment by axw** [comment]
Go 1.16 is over 3.5 years old. I would recommend updating your Go version.

**Comment by adamarbor** [comment]
I also receive this message when using Go 1.20. Potentially an issue with the Go version naming convention change that started with Go 1.21?

**Comment by axw** [comment]
Hi folks, I'm not planning to revert the change to the minimum Go version. If anything I'll update the README to explicitly state that we're supporting only the two most recent Go versions (following Go's own support policy), which is very common among Go projects even if not IMO truly adhering to SemVer.

I very rarely use gocov these days, and have close to zero time to maintain it. The project changes extremely infrequently, so if you don't want to be broken by such changes, my suggestion would be to pin the commit in your go.mod.
