### ISSUE TITLE
gocov test fails when a package is already installed

### ISSUE THREAD

**Issue by orenbenkiki** [axw/gocov#43]
Below is the description I posted on the mailing list. Obviously this doesn't happen to everyone or people would have noticed by now :-) but it is consistently hapening in my case.

If it matters, my disks are NFS-mounted on an IT-managed server that has a daemon running around taking snapshots and so on. I run into a problem with other tools when I discovered that last-modified-date of directories gets changed to the future(!) and back as part of that process. I have no idea if this is relevant here, though, I don't see that dates have anything to do with the problem.

At any rate:

The problem seems to be that if there is an installed version of the being-tested package in my current workspace (which is the only entry in my GOPATH), somehow this version is run instead of the instrumented version in the newly created temporary workspace.

Looking at the source code I see that GOROOT is modified to point at the newly created temporary workspace, and looking at it (by using the --work flag) I see the instrumented package was successfully created there. And yet, the package is taken still taken from the original workspace - that is, from my GOPATH.

The error is, as one would expect:

ok      my/package/name   0.013s
failed to parse gocov output: stat /tmp/gocov072425766/gocov.out: no such file or directory

So, I added a line (next to setting the GOROOT) that sets GOPATH to be the newly created tempDir + ":" + the old value of GOPATH. I figured this will force finding the instrumented package, but this didn't make a difference(!?!?). Just for kicks I changed GOPATH to be only tempDir, and I got the expected warning that GOPATH has no effect, and of course running the tests failed due to missing dependencies - it did find the instrumented package itself though.

**Comment by orenbenkiki** [comment]
I moved on to other projects (it has been almost three years...), so I don't have access to the original environment. If anyone else still has the problem, presumably they'll ask to re-open the issue.

**Comment by axw** [comment]
No worries, and thanks for updating @orenbenkiki.
