### ISSUE TITLE
Installation windows7 fails

### ISSUE THREAD

**Issue by diiimo2k11** [axw/gocov#63]
Install on Win7
go get github.com/axw/gocov/gocov

Error:
C:\Users\timo>go get github.com/axw/gocov/gocov
"# github.com/axw/gocov/gocov"
go\src\github.com\axw\gocov\gocov\convert.go:31: can't open import: "golang.org/
x/tools/cover": Permission denied

**Comment by axw** [comment]
Looks like an ACL issue with your Go installation. What does "go get -x golang.org/x/tools/cover" show?

**Comment by diiimo2k11** [comment]
Problem solved. Was a problem with the Virtual Machine. Have reinstalled Go. In Windows, the GOROOT must be set. Thanks and great tool

**Comment by axw** [comment]
Great, thanks for the update.
