### ISSUE TITLE
gocov's result is different from go test

### ISSUE THREAD

**Issue by xiaoyulei** [axw/gocov#78]
gocov's result is different from ```go test -cover```

this is go test result:
```
EManager.GetClusterRoute         83.33% (20/24)
```

this is gocov result
```
EManager.GetClusterRoute(...) github.com/c/e/e.go 75.00% 
```

**Comment by axw** [comment]
@YuleiXiao can you please provide steps to reproduce the issue? gocov uses "go test -cover" under the hood, so it must have something to do with the interpretation of the data.
