### ISSUE TITLE
please tag a version, to make go modules usage easier 

### ISSUE THREAD

**Issue by soniah** [axw/gocov#83]
https://blog.golang.org/using-go-modules

eg `git tag v1.0.0`

FYI for others here's a version string: `v0.0.0-20170322000131-3a69a0d2a4ef`

**Comment by axw** [comment]
Done: https://github.com/axw/gocov/releases/tag/v1.0.0

Thanks for opening the issue.

**Comment by soniah** [comment]
Legend! ✅ Thanks!
