### ISSUE TITLE
Unable to use go install

### ISSUE THREAD

**Issue by hurrycaner** [axw/gocov#94]
I'm trying to use `go install github.com/axw/gocov/gocov` but i'm getting the following error:
```
$ go install github.com/axw/gocov/gocov
no required module provides package github.com/axw/gocov/gocov; to add it:
        go get github.com/axw/gocov/gocov
```
I've tried in different environments (local and CI) and they are giving the same error.
I've tried `go install github.com/axw/gocov` too, but i get similar message.

Btw, i'm using go 1.17.10

**Comment by hurrycaner** [comment]
Okay, using `go install github.com/axw/gocov/gocov@v1.1.0` works flawlessly, would be nice to update readme :)

**Comment by axw** [comment]
Updated the readme in https://github.com/axw/gocov/commit/12cc591a77f7fafee67354702a066aad06870d67

Without the suffix, the module must be specified in your project's `go.mod`.
